services:

  gezagproxymock:
    container_name: gezagproxymock
    image: ghcr.io/brp-api/gezag-proxy-mock:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5130
      - Routes__0__DownstreamScheme=http
      - Routes__0__DownstreamHostAndPorts__0__Host=gezagmock
      - Routes__0__DownstreamHostAndPorts__0__Port=5020
    ports:
      - "5130:5130"
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network