services:

  gezagmock:
    container_name: gezagmock
    image: ghcr.io/MelvLee/gezag-mock:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5020
    ports:
      - "5020:5020"
    # volumes:
    #   - ../test-data/GezagMock/test-data.json:/app/Data/test-data.json
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
